services:
  db-service:
    build:
      context: ./db-service
      dockerfile: Dockerfile
    ports:
      - "${DB_SERVICE_PORT}:${DB_SERVICE_PORT}"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=db
      - POSTGRES_PORT=${POSTGRES_PORT}
      - PORT=${DB_SERVICE_PORT}
    volumes:
      - ./db-service:/app
    depends_on:
      - db

  youtube-audio-service:
    build:
      context: ./youtube-audio-service
      dockerfile: Dockerfile
    ports:
      - "${YOUTUBE_AUDIO_SERVICE_PORT}:${YOUTUBE_AUDIO_SERVICE_PORT}"
    environment:
      - DB_SERVICE_URL=http://db-service:${DB_SERVICE_PORT}
      - AUDIO_DIR=/downloaded_audio
      - PORT=${YOUTUBE_AUDIO_SERVICE_PORT}
    volumes:
      - ./${AUDIO_DIR}:/downloaded_audio
      - ./youtube-audio-service:/app
    depends_on:
      - db-service

  audio-text-service:
    build:
      context: ./audio-text-service
      dockerfile: Dockerfile
    ports:
      - "${AUDIO_TEXT_SERVICE_PORT}:${AUDIO_TEXT_SERVICE_PORT}"
    environment:
      - DB_SERVICE_URL=http://db-service:${DB_SERVICE_PORT}
      - AUDIO_DIR=/downloaded_audio
      - TEXT_DIR=/downloaded_text
      - HF_TOKEN=${HF_TOKEN}
      - PORT=${AUDIO_TEXT_SERVICE_PORT}
    volumes:
      - ./${AUDIO_DIR}:/downloaded_audio
      - ./${TEXT_DIR}:/downloaded_text
      - ./audio-text-service:/app
    depends_on:
      - db-service
      - youtube-audio-service

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "${QDRANT_PORT}:${QDRANT_PORT}"
    volumes:
      - qdrant_data:/qdrant/storage

  qdrant-admin:
    build:
      context: ./qdrant-admin
      dockerfile: Dockerfile
    ports:
      - "8007:8007"
    depends_on:
      - qdrant
volumes:
  postgres_data:
  qdrant_data: